apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-service
  labels:
    app: client-service
    visualize: "true"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
        version: "v1"
        visualize: "true"     
    spec:
      containers:
      - name: client-service
        image: client-service:v1
        imagePullPolicy: Never
        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"        
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
        ports:
        - name: http
          containerPort: 9999          
---

apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    name: client-service
    visualize: "true"
spec:
  type: NodePort
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  sessionAffinity: None    
---


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-service
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50    