server:
  port: 8765


info:
  app:
    name: Eurea client service
    description: Client Service spring boot application
    version: 1.0.0
---
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}      

---

spring:
  profiles: cloud
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}/eureka        